backend:
  name: git-gateway
  repo: RedCiudadana/Link-Tree
  branch: main
  identity_url: https://auth.decapbridge.com/sites/85e72631-206b-47d2-9427-05fe8672026f
  gateway_url: https://gateway.decapbridge.com

  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "bloque_principal"
    label: "Bloque Principal"
    folder: "src/content/bloque_principal"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Foto", name: "foto", widget: "image", required: true }
      - { label: "Título", name: "titulo", widget: "string", required: true }
      - { label: "Subtítulo", name: "subtitulo", widget: "string", required: true }
      - { label: "Texto del botón", name: "texto_boton", widget: "string", required: true }
      - { label: "Enlace del botón", name: "enlace_boton", widget: "string", required: true }
  - name: "aprende_red_ciudadana"
    label: "Aprende con Red Ciudadana"
    folder: "src/content/aprende_red_ciudadana"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Foto", name: "foto", widget: "image", required: true }
      - { label: "Título", name: "titulo", widget: "string", required: true }
      - { label: "Subtítulo", name: "subtitulo", widget: "string", required: true }
      - { label: "Enlace del botón", name: "enlace_boton", widget: "string", required: true }
  - name: "explora_plataformas"
    label: "Explora nuestras plataformas"
    folder: "src/content/explora_plataformas"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Foto", name: "foto", widget: "image", required: true }
      - { label: "Título", name: "titulo", widget: "string", required: true }
      - { label: "Subtítulo", name: "subtitulo", widget: "string", required: true }
      - { label: "Enlace del botón", name: "enlace_boton", widget: "string", required: true }
